// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjPyjI-C3JyY7QoMVTI11oe01h8oenNrc',
    appId: '1:1003688476075:web:325732aa0e5ec0722fe6ee',
    messagingSenderId: '1003688476075',
    projectId: 'dokanpart-351c5',
    authDomain: 'dokanpart-351c5.firebaseapp.com',
    storageBucket: 'dokanpart-351c5.appspot.com',
    measurementId: 'G-4P2DVL4SQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_o3e0NEu8915Vsnowmm8F9vT0wSFh_ss',
    appId: '1:1003688476075:android:df8e105a9b2627a82fe6ee',
    messagingSenderId: '1003688476075',
    projectId: 'dokanpart-351c5',
    storageBucket: 'dokanpart-351c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJNk8TS5I0z0pZ3UXMlcewNgyc4FXlwI',
    appId: '1:1003688476075:ios:31722e16a89aaeb22fe6ee',
    messagingSenderId: '1003688476075',
    projectId: 'dokanpart-351c5',
    storageBucket: 'dokanpart-351c5.appspot.com',
    iosClientId:
        '1003688476075-2i10jk3c95pnn7p0p11vlec85dqhigpq.apps.googleusercontent.com',
    iosBundleId: 'com.dokanpat.bd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJNk8TS5I0z0pZ3UXMlcewNgyc4FXlwI',
    appId: '1:1003688476075:ios:31722e16a89aaeb22fe6ee',
    messagingSenderId: '1003688476075',
    projectId: 'dokanpart-351c5',
    storageBucket: 'dokanpart-351c5.appspot.com',
    iosClientId:
        '1003688476075-2i10jk3c95pnn7p0p11vlec85dqhigpq.apps.googleusercontent.com',
    iosBundleId: 'com.dokanpat.bd',
  );
}
