final List Bdstate = [
  {"id": "BD-00", "name": "Select Your Location", "country_id": "18"},
  {"id": "BD-05", "name": "Bagar Hat", "country_id": "18"},
  {"id": "BD-01", "name": "Bandarban", "country_id": "18"},
  {"id": "BD-02", "name": "Barguna", "country_id": "18"},
  {"id": "BD-06", "name": "Barisal", "country_id": "18"},
  {"id": "BD-07", "name": "Bhola", "country_id": "18"},
  {"id": "BD-03", "name": "Bogora", "country_id": "18"},
  {"id": "BD-04", "name": "Brahman Bariya", "country_id": "18"},
  {"id": "BD-09", "name": "Chandpur", "country_id": "18"},
  {"id": "BD-10", "name": "Chattogram", "country_id": "18"},
  {"id": "BD-12", "name": "Chuadanga", "country_id": "18"},
  {"id": "BD-11", "name": "Cox Bazar", "country_id": "18"},
  {"id": "BD-08", "name": "Cumilla", "country_id": "18"},
  {"id": "BD-13", "name": "Dhaka", "country_id": "18"},
  {"id": "BD-14", "name": "Dinajpur", "country_id": "18"},
  {"id": "BD-15", "name": "Faridpur", "country_id": "18"},
  {"id": "BD-16", "name": "Feni", "country_id": "18"},
  {"id": "BD-19", "name": "Gaibandha", "country_id": "18"},
  {"id": "BD-18", "name": "Gazipur", "country_id": "18"},
  {"id": "BD-17", "name": "Gopalganj", "country_id": "18"},
  {"id": "BD-20", "name": "Habiganj", "country_id": "18"},
  {"id": "BD-24", "name": "Joypurhat", "country_id": "18"},
  {"id": "BD-21", "name": "Jamalpur", "country_id": "18"},
  {"id": "BD-22", "name": "Jessor", "country_id": "18"},
  {"id": "BD-25", "name": "Jhalokati", "country_id": "18"},
  {"id": "BD-23", "name": "Jhenaidah", "country_id": "18"},
  {"id": "BD-29", "name": "Khagrachhari", "country_id": "18"},
  {"id": "BD-27", "name": "Khulna", "country_id": "18"},
  {"id": "BD-26", "name": "Kishoreganj", "country_id": "18"},
  {"id": "BD-28", "name": "Kurigram", "country_id": "18"},
  {"id": "BD-30", "name": "Kushtiya", "country_id": "18"},
  {"id": "BD-31", "name": "Kushtia", "country_id": "18"},
  {"id": "BD-31", "name": "Lakshmipur", "country_id": "18"},
  {"id": "BD-32", "name": "Lalmonirhat", "country_id": "18"},
  {"id": "BD-36", "name": "Madaripur", "country_id": "18"},
  {"id": "BD-37", "name": "Magura", "country_id": "18"},
  {"id": "BD-33", "name": "Manikganj", "country_id": "18"},
  {"id": "BD-39", "name": "Meherpur", "country_id": "18"},
  {"id": "BD-38", "name": "Moulvibazar", "country_id": "18"},
  {"id": "BD-35", "name": "Munshiganj", "country_id": "18"},
  {"id": "BD-34", "name": "Mymensingh", "country_id": "18"},
  {"id": "BD-48", "name": "Naogaon", "country_id": "18"},
  {"id": "BD-43", "name": "Narail", "country_id": "18"},
  {"id": "BD-40", "name": "Narayanganj", "country_id": "18"},
  {"id": "BD-42", "name": "Narsingdi", "country_id": "18"},
  {"id": "BD-44", "name": "Natore", "country_id": "18"},
  {"id": "BD-45", "name": "Nawabganj", "country_id": "18"},
  {"id": "BD-41", "name": "Netrakona", "country_id": "18"},
  {"id": "BD-46", "name": "Nilphamari", "country_id": "18"},
  {"id": "BD-47", "name": "Noakhali", "country_id": "18"},
  {"id": "BD-49", "name": "Pabna", "country_id": "18"},
  {"id": "BD-52", "name": "Panchagarh", "country_id": "18"},
  {"id": "BD-52", "name": "Patuakhali", "country_id": "18"},
  {"id": "BD-50", "name": "Pirojpur", "country_id": "18"},
  {"id": "BD-53", "name": "Rajbari", "country_id": "18"},
  {"id": "BD-54", "name": "Rajshahi", "country_id": "18"},
  {"id": "BD-56", "name": "Rangamati", "country_id": "18"},
  {"id": "BD-55", "name": "Rangpur", "country_id": "18"},
  {"id": "BD-58", "name": "Satkhira", "country_id": "18"},
  {"id": "BD-62", "name": "Shariatpur", "country_id": "18"},
  {"id": "BD-57", "name": "Sherpur", "country_id": "18"},
  {"id": "BD-59", "name": "Sirajganj", "country_id": "18"},
  {"id": "BD-61", "name": "Sunamganj", "country_id": "18"},
  {"id": "BD-60", "name": "Sylhet", "country_id": "18"},
  {"id": "BD-63", "name": "Tangail", "country_id": "18"},
  {"id": "BD-64", "name": "Thakurgaon", "country_id": "18"},
];
